avidity/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('comics.urls')),
    url(r'^admin/', admin.site.urls),
]

comics/urls.py
from django.conf.urls import include, url

from . import views

app_name = 'comics'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search/$', views.search, name='search'),
    url(r'^character/(?P<char_id>[0-9]+)/$', views.character, name='character'),
    url(r'^comic/(?P<comic_id>[0-9]+)/$', views.comic, name='comic'),
]

comics/models.py
from django.db import models

# Create your models here.

comics/forms.py
from django import forms
from django.forms import ModelForm

class NameForm(forms.Form):
    char_name = forms.CharField(max_length=100)

comics/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader

from .forms import NameForm
from .external import Marvel

def index(request):
    template = loader.get_template('comics/base.html')
    context = {}
    if request.method == 'POST':
        form = NameForm(request.POST)
        if form.is_valid():
            context, template = search(request)
    else:
        form = NameForm()
    context['form'] = form
    return HttpResponse(template.render(context, request))

def search(request):
    template = loader.get_template('comics/list_char.html')
    char_name = request.POST.get('char_name', '')
    list_char = Marvel().get_characteres(char_name)
    if list_char:
        context = {
            'char_name' : char_name,
            'list_char' : list_char
        }
    else:
        context = {}
    return context, template

def character(request, char_id):
    template = loader.get_template('comics/char.html')
    char, attribution_text = Marvel().get_id(char_id)
    char_comics = Marvel().get_id_comics(char_id)
    context = {
        'form' : NameForm(),
        'char_id' : char,
        'char_comics' : char_comics,
        'attr' : attribution_text
    }
    return HttpResponse(template.render(context, request))

def comic(request, comic_id):
    template = loader.get_template('comics/comics.html')
    comic, attribution_text = Marvel().get_comics(comic_id)
    comic_char = Marvel().get_comics_characters(comic_id)
    context = {
        'form' : NameForm(),
        'comic' : comic,
        'comic_char' : comic_char,
        'attr' : attribution_text
    }
    return HttpResponse(template.render(context, request))

comics/templates/comics/base.html
{% load static %}
{% load widget_tweaks %}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}


<body>
  <div class="col-lg-offset-3 col-lg-6">
    <h1><a href="{% url 'comics:index' %}"> Marvel Comics </a></h1>
    <form action="{% url 'comics:index' %}" method="post">
      {% csrf_token %}
      <div class="input-group">
        {{form.char_name|add_class:"form-control"}}
        <div class="input-group-btn">
          <div class="btn-group">
            <button class="btn btn-default" type="button">Search</button>
          </div>
        </div>
      </div>
    </form>
      {% block content %}
      {% endblock %}
  </div><!-- /.col-lg-6 -->
<body>

comics/templates/comics/char.html
{% extends 'comics/base.html' %}
{% load comics_tags %}

{% block content %}
  <div class="row">
    {% if char_id %}
      <div class="col-lg-4">
        {# {{char_id.thum}}#}
        <img src="{{ char_id.thumbnail.path }}/portrait_fantastic.jpg">
      </div>
      <div class="col-lg-8">
        <div class="row">
          <h2>{{ char_id.name }}</h2>
          {% if char_id.description %}
            {{ char_id.description }}
          {% else %}
            No description available
          {% endif %}
          <br>
        </div>
      </div>
    </div>
    <div class="row">
      <h3>Comics</h3>
      {% if char_comics %}
        <ul class="list-group">
          {% for comic in char_comics %}
            <a class="list-group-item" href="{% url 'comics:comic' comic_id=comic.id %}">
              <img src="{{ comic.thumbnail.path }}/portrait_small.jpg">
              {{comic.title}}
            </a>
          {% endfor %}
        </ul>
      {% else %}
        No stories available
      {% endif %}
    </div>
    {{ attr }}
  {% else %}
    <h3>Sorry, something went wrong. The character could not be loaded</h3>
  {% endif %}
{% endblock %}

comics/templates/comics/comics.html
{% extends 'comics/base.html' %}

{% block content %}
  <div class="row">
  {% if comic %}
    <div class="col-lg-4">
      <img src="{{ comic.thumbnail.path }}/portrait_fantastic.jpg">
    </div>
    <div class="col-lg-8">
      <div class="row">
        <h2>{{ comic.title }}</h2>
        {% if comic.description %}
          {{ comic.description }}
        {% else %}
          No description available
        {% endif %}
      </div>
    </div>
  </div>
  <div class="row">
    <h3>Characters</h3>
    <ul class="list-group">
      {% for char in comic_char %}
        <a class="list-group-item"
          href="{% url 'comics:character' char_id=char.id %}">
          <img src="{{ char.thumbnail.path }}/portrait_small.jpg">
          {{char.name}}
        </a>
      {% endfor %}
    </ul>
  </div>
  {{ attr }}
  {% else %}
    <h3>Sorry, something went wrong. The comic could not be loaded</h3>
  {% endif %}
<div>
{% endblock %}

comics/templates/comics/index.html
{% extends 'comics/base.html' %}

comics/templates/comics/list.html
{% load static %}
{% load widget_tweaks %}
<link rel="stylesheet" type="text/css" href="{% static 'comics/bootstrap.min.css' %}" />
<div class="col-lg-offset-3 col-lg-6">
  {% if list_char.data.count %}
    <ul class="list-group">
      {% for char in list_char.data.results %}
        <a class="list-group-item" href="{% url 'comics:character' char_id=char.id %}">
          <img src="{{ char.thumbnail.path }}/portrait_small.jpg">
          {{ char.name }}
        </a>
      {% endfor %}
    </ul>
    {{ list_char.attributionText }}
  {% else %}
    <li>Sorry, no characters found.</li>
  {% endif %}
</div>

comics/templates/comics/list_char.html
{% extends 'comics/base.html' %}

{% block content %}
<div>
  {% if list_char.count %}
    <ul class="list-group">
      {% for char in list_char.results %}
        <a class="list-group-item" href="{% url 'comics:character' char_id=char.id %}">
          <img src="{{ char.thumbnail.path }}/portrait_small.jpg">
          {{ char.name }}
        </a>
      {% endfor %}
    </ul>
    {{ list_char.attributionText }}
  {% else %}
    {% if list_char %}
      <h3>Sorry, no characters found.</h3>
    {% else %}
      <h3>Sorry, something went wrong. A list of characters were not retreived</h3>
    {% endif %}
  {% endif %}
</div>
{% endblock %}

comics/templates/comics/story.html
{% load static %}
{% load widget_tweaks %}
{% load comics_tags %}

<link rel="stylesheet" type="text/css" href="{% static 'comics/bootstrap.min.css' %}" />
<div class="col-lg-offset-3 col-lg-6">
  <div class="col-lg-4">
    <img src="{{ story.thumbnail.path }}/portrait_fantastic.jpg">
  </div>
  <div class="col-lg-8">
    <div class="row">
      <h2>{{ story.title }}</h2>
      {% if story.description %}
        {{ story.description }}
      {% else %}
        No description available
      {% endif %}
    </div>
  </div>
  <div class="row">
    <h3>Characters</h3>
    <ul class="list-group">
      {# {{char.stories}}#}
      {% for char in story_char %}
        <a class="list-group-item"
          href="{% url 'comics:character' char_id=char.id %}">
          <img src="{{ char.thumbnail.path }}/portrait_small.jpg">
          {{char.name}}
        </a>
      {% endfor %}
    </ul>
  </div>
  {{ attr }}
<div>